import { Navigation } from "@/components/Navigation";
import "./globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "seblee.dev",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} p-8 h-screen`}>
        <header>
          <Navigation />
        </header>
        <main className="h-full">{children}</main>
      </body>
    </html>
  );
}
